In [ ]:
import pyodbc
import pandas as pd
import numpy as np
from datetime import datetime
from sklearn.preprocessing import LabelEncoder

In [ ]:
cnxn_str = ("Driver={SQL Server Native Client 11.0};"
            "Server=LAPTOP-CTTVUGH7;"
            "Database=joint s p v;"
            "Trusted_Connection=yes;")

cnxn = pyodbc.connect(cnxn_str)

In [ ]:
cursor = cnxn.cursor()

In [ ]:
Vehicule = pd.read_sql("SELECT * FROM [vv1]", cnxn)
Police = pd.read_sql("SELECT * FROM [pp]", cnxn)

In [ ]:
cnxn_str1 = ("Driver={SQL Server Native Client 11.0};"
            "Server=LAPTOP-CTTVUGH7;"
            "Database=CGA_ODS;"
            "Trusted_Connection=yes;")

cnxn1 = pyodbc.connect(cnxn_str1)

In [ ]:
BonusMalus = pd.read_sql("SELECT * FROM [ClassesBonusMalus]", cnxn1)

In [ ]:
BonusMalus

,CodeBonusMalus_id,CodePolice_id,CodeVehicule_id,CodeAssure_id,CodeSouscripteur_id,codeUsage,ETAT_VEHICULE,DATE_AFFECTATION,classeBonusMalus,classeBonusMalusCompagnie,coefBonusMalus
0,117346,116167,111858,101772,101691,1,V,2017-07-14 00:00:00,1,1,70
1,117347,116168,111859,99417,99336,10,V,2017-07-14 00:00:00,1,1,80
2,117348,116169,111860,101773,101692,1,V,2017-07-14 00:00:00,1,1,70
3,117349,116170,111861,101774,101693,1,V,2017-07-14 00:00:00,1,1,70
4,117350,116171,111862,101775,101694,1,V,2017-07-14 00:00:00,2,2,80
...,...,...,...,...,...,...,...,...,...,...,...
1307356,1302912,1298035,681961,959384,959395,1,V,2017-08-22 00:00:00,8,8,200
1307357,1302913,1298036,685316,1014694,1014707,3,V,2016-12-21 00:00:00,5,5,150
1307358,1302914,1298037,1010766,1014694,1014707,2,V,2017-05-30 00:00:00,5,5,150
1307359,1302915,1298038,348083,1014694,1014707,1,V,2017-11-11 00:00:00,5,5,120
1307360,1302916,1298039,206544,959391,959402,1,V,2017-09-21 00:00:00,4,4,100

In [ ]:
BonusMalus.duplicated(subset=['CodeBonusMalus_id']).sum()

0

In [ ]:
#merge  and vehicule
a=pd.merge(BonusMalus, Vehicule, on='CodeVehicule_id', how='left')

In [ ]:
#merge ,vehicule and Police
BonusMalus=pd.merge(a, Police, on='CodePolice_id', how='left')

In [ ]:
BonusMalus

,CodeBonusMalus_id,CodePolice_id,CodeVehicule_id,CodeAssure_id,CodeSouscripteur_id,codeUsage,ETAT_VEHICULE,DATE_AFFECTATION,classeBonusMalus,classeBonusMalusCompagnie,...,dateEffetPolice,dateEcheancePolice,dateExpirationPolice,verouillageModifPolice,Etat_Police,RESILIATION_ECHEANCE,DATE_RESILIATION,Date_Suspenssion,dateRemiseEnVigueure,F1_y
0,117346,116167,111858,101772,101691,1,V,2017-07-14 00:00:00,1,1,...,2017-07-14,714.0,None,NaN,V,None,None,None,None,NaN
1,117347,116168,111859,99417,99336,10,V,2017-07-14 00:00:00,1,1,...,2017-07-14,714.0,None,NaN,V,None,None,None,None,NaN
2,117348,116169,111860,101773,101692,1,V,2017-07-14 00:00:00,1,1,...,2017-07-14,714.0,None,NaN,V,None,None,None,None,NaN
3,117349,116170,111861,101774,101693,1,V,2017-07-14 00:00:00,1,1,...,2017-07-14,714.0,None,NaN,V,None,None,None,None,NaN
4,117350,116171,111862,101775,101694,1,V,2017-07-14 00:00:00,2,2,...,2017-07-14,714.0,None,NaN,V,None,None,None,None,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1307356,1302912,1298035,681961,959384,959395,1,V,2017-08-22 00:00:00,8,8,...,2017-08-22,822.0,None,NaN,V,None,None,None,None,NaN
1307357,1302913,1298036,685316,1014694,1014707,3,V,2016-12-21 00:00:00,5,5,...,2016-03-10,310.0,None,NaN,R,None,None,None,None,NaN
1307358,1302914,1298037,1010766,1014694,1014707,2,V,2017-05-30 00:00:00,5,5,...,2017-02-01,201.0,None,NaN,R,None,None,None,None,NaN
1307359,1302915,1298038,348083,1014694,1014707,1,V,2017-11-11 00:00:00,5,5,...,2017-05-31,531.0,None,NaN,R,None,None,None,None,NaN
1307360,1302916,1298039,206544,959391,959402,1,V,2017-09-21 00:00:00,4,4,...,2016-09-21,921.0,None,NaN,V,None,None,None,None,NaN

In [ ]:
BonusMalus.duplicated(subset=['CodeBonusMalus_id']).sum()

0

In [ ]:
for i in BonusMalus:
    print(BonusMalus[i].name+' :'+str(BonusMalus[i].value_counts().sum()))

CodeBonusMalus_id :1307361
CodePolice_id :1307361
CodeVehicule_id :1307361
CodeAssure_id :1307361
CodeSouscripteur_id :1307361
codeUsage :1307361
ETAT_VEHICULE :1307361
DATE_AFFECTATION :1307361
classeBonusMalus :1307361
classeBonusMalusCompagnie :1307361
coefBonusMalus :1307361
index :1307361
F1_x :9415
numChassis :9415
codeMarque :1307361
puissanceFiscal :1307361
numImmatriculation :9415
typeImmatriculation :1307361
energie :1307361
dateInsertion :1307361
dateDerniereVisite :4
dateAjout :9415
etatVehicule :9415
dateMiseEpave :0
DATE_RETRAIT :0
dateMiseCirculation :0
dateMiseAjourVehicule :4
codeCompagnie :1307361
codeAgence :1307361
typeIntermediaire :1307361
code_Courtier_CGA :0
numPolice :1307361
naturePolice :1307361
typePolice :1307361
dateEffetPolice :1307361
dateEcheancePolice :1165479
dateExpirationPolice :0
verouillageModifPolice :0
Etat_Police :1307361
RESILIATION_ECHEANCE :0
DATE_RESILIATION :0
Date_Suspenssion :0
dateRemiseEnVigueure :0
F1_y :0

In [ ]:
x=(BonusMalus["classeBonusMalusCompagnie"]==BonusMalus["classeBonusMalus"])

In [ ]:
x.value_counts()

True     1307263
False         98
dtype: int64

In [ ]:

#F1_x :9415
#numChassis :9415
#numImmatriculation :9415
#dateDerniereVisite :4
#dateAjout :9415
#etatVehicule :9415
#dateMiseEpave :0
#DATE_RETRAIT :0
#dateMiseCirculation :0
#dateMiseAjourVehicule :4
#code_Courtier_CGA :0
#dateExpirationPolice :0
#verouillageModifPolice :0
#Etat_Police :1307361
#RESILIATION_ECHEANCE :0
#DATE_RESILIATION :0
#Date_Suspenssion :0
#dateRemiseEnVigueure :0
#F1_y :0
fait_BM = fait_BM.drop(['index','F1_y','F1_x','CodeSouscripteur_id','classeBonusMalusCompagnie','numChassis'
                         ,'numImmatriculation','dateDerniereVisite','dateAjout','etatVehicule'
                         ,'dateMiseEpave','DATE_RETRAIT','dateMiseCirculation','dateMiseAjourVehicule'
                        ,'code_Courtier_CGA','numPolice','dateEffetPolice','dateEcheancePolice',
                        'dateExpirationPolice','verouillageModifPolice','RESILIATION_ECHEANCE','DATE_RESILIATION'
                             ,'Date_Suspenssion','dateRemiseEnVigueure'], axis=1)

In [ ]:
BonusMalus

,CodeBonusMalus_id,CodePolice_id,CodeVehicule_id,CodeAssure_id,codeUsage,ETAT_VEHICULE,DATE_AFFECTATION,classeBonusMalus,coefBonusMalus,codeMarque,puissanceFiscal,typeImmatriculation,energie,dateInsertion,codeCompagnie,codeAgence,typeIntermediaire,naturePolice,typePolice,Etat_Police
0,117346,116167,111858,101772,1,V,2017-07-14 00:00:00,1,70,29.0,6.0,TU,ESSENCE,2017-10-05,12.0,07A,1.0,R,I,V
1,117347,116168,111859,99417,10,V,2017-07-14 00:00:00,1,80,1672.0,33.0,ES,GASOIL,2017-10-05,12.0,20Z,1.0,R,I,V
2,117348,116169,111860,101773,1,V,2017-07-14 00:00:00,1,70,105.0,5.0,TU,ESSENCE,2017-10-05,12.0,12W,2.0,R,I,V
3,117349,116170,111861,101774,1,V,2017-07-14 00:00:00,1,70,29.0,4.0,TU,ESSENCE,2017-10-05,12.0,12W,2.0,R,I,V
4,117350,116171,111862,101775,1,V,2017-07-14 00:00:00,2,80,107.0,6.0,TU,GASOIL,2017-10-05,12.0,53B,1.0,R,I,V
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1307356,1302912,1298035,681961,959384,1,V,2017-08-22 00:00:00,8,200,152.0,6.0,TU,ESSENCE,2017-10-05,11.0,126,2.0,R,I,V
1307357,1302913,1298036,685316,1014694,3,V,2016-12-21 00:00:00,5,150,96.0,10.0,TU,GASOIL,2017-10-05,11.0,194,1.0,R,I,R
1307358,1302914,1298037,1010766,1014694,2,V,2017-05-30 00:00:00,5,150,119.0,5.0,TU,GASOIL,2017-10-05,11.0,194,1.0,R,I,R
1307359,1302915,1298038,348083,1014694,1,V,2017-11-11 00:00:00,5,120,338.0,7.0,TU,ESSENCE,2017-10-30,11.0,194,1.0,R,I,R
1307360,1302916,1298039,206544,959391,1,V,2017-09-21 00:00:00,4,100,30.0,5.0,TU,ESSENCE,2017-10-05,11.0,180,2.0,R,I,V

In [ ]:
BonusMalus.dtypes

CodeBonusMalus_id        int64
CodePolice_id            int64
CodeVehicule_id          int64
CodeAssure_id            int64
codeUsage                int64
ETAT_VEHICULE           object
DATE_AFFECTATION        object
classeBonusMalus         int64
coefBonusMalus           int64
codeMarque             float64
puissanceFiscal        float64
typeImmatriculation     object
energie                 object
dateInsertion           object
codeCompagnie          float64
codeAgence              object
typeIntermediaire      float64
naturePolice            object
typePolice              object
Etat_Police             object
dtype: object

In [ ]:
#ajout de colonne de fraud
BonusMalus['Fraud']=0

In [ ]:
#visualisation de la colonne sinistre
BonusMalus['Fraud']

0          0
1          0
2          0
3          0
4          0
          ..
1307356    0
1307357    0
1307358    0
1307359    0
1307360    0
Name: Fraud, Length: 1307361, dtype: int64

In [ ]:
BonusMalus.dtypes

CodeBonusMalus_id        int64
CodePolice_id            int64
CodeVehicule_id          int64
CodeAssure_id            int64
codeUsage                int64
ETAT_VEHICULE           object
DATE_AFFECTATION        object
classeBonusMalus         int64
coefBonusMalus           int64
codeMarque             float64
puissanceFiscal        float64
typeImmatriculation     object
energie                 object
dateInsertion           object
codeCompagnie          float64
codeAgence              object
typeIntermediaire      float64
naturePolice            object
typePolice              object
Etat_Police             object
Fraud                    int64
dtype: object

In [ ]:
#x=BonusMalus["CodeVehicule_id"].value_counts()

In [ ]:
import sqlalchemy
engine = sqlalchemy.create_engine("mssql+pyodbc://DESKTOP-9NKKJ4N/ss1 vv1 pp lkol unique?driver=SQL Server?Trusted_Connection=yes")
conn = engine.connect()

In [ ]:
BonusMalus.to_sql('BonusMalus', conn, if_exists='replace')

In [ ]:
#detectionde fraud si le typepolice est individuelle et le client a plusieurs voiture
#cursor.execute("SELECT count(CodeVehicule_id) as count,CodeVehicule_id FROM BonusMalus where typePolice='I' group by CodeVehicule_id having count(CodeVehicule_id) =10 ")

In [ ]:
query = "SELECT count(CodeVehicule_id) as count,CodeVehicule_id FROM BonusMalus where typePolice='I' group by CodeVehicule_id having count(CodeVehicule_id) >=2 "
results = cursor.execute(query).fetchall()

In [ ]:
x=0
for i in results:
    x=x+1
print(x)

179722

In [ ]:
dataframe = pd.read_sql(query, con = conn)

In [ ]:
dataframe

        count  CodeVehicule_id
0           2           200709
1           2           546648
2           2           202944
3           2           243959
4           2            83394
...       ...              ...
179717      2           689385
179718      2           326210
179719      2           835831
179720      2           147947
179721      2           995911

[179722 rows x 2 columns]

In [ ]:
condition=(BonusMalus["CodeVehicule_id"].isin(dataframe["CodeVehicule_id"]))

In [ ]:
condition.value_counts()

False    921670
True     385691
Name: CodeVehicule_id, dtype: int64

In [ ]:
BonusMalus.loc[condition,'Fraud']=1

In [ ]:
BonusMalus['Fraud'].value_counts()

0    921670
1    385691
Name: Fraud, dtype: int64

In [ ]:
BonusMalus[BonusMalus['Fraud']==1]

,CodeBonusMalus_id,CodePolice_id,CodeVehicule_id,CodeAssure_id,codeUsage,ETAT_VEHICULE,DATE_AFFECTATION,classeBonusMalus,coefBonusMalus,codeMarque,...,typeImmatriculation,energie,dateInsertion,codeCompagnie,codeAgence,typeIntermediaire,naturePolice,typePolice,Etat_Police,Fraud
24,117370,116191,111882,101793,1,V,2017-07-14 00:00:00,3,90,30.0,...,TU,ESSENCE,2017-10-06,12.0,20Z,1.0,R,I,V,1
29,117375,116196,111887,101798,1,V,2017-07-14 00:00:00,4,100,29.0,...,TU,ESSENCE,2017-10-05,12.0,06E,1.0,R,I,V,1
88,117434,116255,111946,101851,1,V,2017-07-15 00:00:00,5,120,29.0,...,TU,ESSENCE,2017-10-05,12.0,53X,1.0,R,I,V,1
96,117442,116263,111954,101858,1,V,2017-07-15 00:00:00,3,90,107.0,...,TU,GASOIL,2017-10-05,12.0,53K,1.0,R,I,V,1
99,117445,116266,111957,101860,1,V,2017-07-15 00:00:00,3,90,107.0,...,TU,ESSENCE,2017-10-05,12.0,52V,1.0,R,I,V,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1307356,1302912,1298035,681961,959384,1,V,2017-08-22 00:00:00,8,200,152.0,...,TU,ESSENCE,2017-10-05,11.0,126,2.0,R,I,V,1
1307357,1302913,1298036,685316,1014694,3,V,2016-12-21 00:00:00,5,150,96.0,...,TU,GASOIL,2017-10-05,11.0,194,1.0,R,I,R,1
1307358,1302914,1298037,1010766,1014694,2,V,2017-05-30 00:00:00,5,150,119.0,...,TU,GASOIL,2017-10-05,11.0,194,1.0,R,I,R,1
1307359,1302915,1298038,348083,1014694,1,V,2017-11-11 00:00:00,5,120,338.0,...,TU,ESSENCE,2017-10-30,11.0,194,1.0,R,I,R,1
1307360,1302916,1298039,206544,959391,1,V,2017-09-21 00:00:00,4,100,30.0,...,TU,ESSENCE,2017-10-05,11.0,180,2.0,R,I,V,1

In [ ]:
# test dans le dataframe fraud : client id= 111946
dataframe[dataframe["CodeVehicule_id"]==111946]

       count  CodeVehicule_id
43370      3           111946

In [ ]:
#save fraud changes to database
#BonusMalus.to_sql('BonusMalus', conn, if_exists='replace')

In [ ]:
#detection fraud si codeusage =1 prive donc type usage doi etre I sinon fraud

In [ ]:
query = "SELECT CodeVehicule_id FROM BonusMalus where codeUsage=1 and typePolice='F' "
results = cursor.execute(query).fetchall()

In [ ]:
dataframe = pd.read_sql(query, con = conn)

In [ ]:
dataframe

      CodeVehicule_id
0              303523
1              303524
2              303525
3              303527
4              303530
...               ...
4125          1030208
4126          1030209
4127          1030210
4128          1030211
4129          1030212

[4130 rows x 1 columns]

In [ ]:
condition=(BonusMalus["CodeVehicule_id"].isin(dataframe["CodeVehicule_id"]))

In [ ]:
condition.value_counts()

False    1302415
True        4946
Name: CodeVehicule_id, dtype: int64

In [ ]:
BonusMalus.loc[condition,'Fraud']=1

In [ ]:
BonusMalus['Fraud'].value_counts()

0    916998
1    390363
Name: Fraud, dtype: int64

In [ ]:
# test de fraud dans le dataframe bonusmalus : CodeVehicule_id= 303523
BonusMalus[BonusMalus["CodeVehicule_id"]==303523]

,CodeBonusMalus_id,CodePolice_id,CodeVehicule_id,CodeAssure_id,codeUsage,ETAT_VEHICULE,DATE_AFFECTATION,classeBonusMalus,coefBonusMalus,codeMarque,...,typeImmatriculation,energie,dateInsertion,codeCompagnie,codeAgence,typeIntermediaire,naturePolice,typePolice,Etat_Police,Fraud
396823,359041,357861,303523,300600,1,V,2018-01-01 00:00:00,2,80,107.0,...,TU,ESSENCE,2017-10-05,2.0,559,3.0,R,F,V,1

In [ ]:
#save fraud changes to database
#BonusMalus.to_sql('BonusMalus', conn, if_exists='replace')

In [ ]:
#detection fraud si codeusage =1 prive donc type usage doi etre I sinon fraud

In [ ]:
query = "SELECT CodeVehicule_id FROM BonusMalus where codeUsage=15 and typePolice='I' "
results = cursor.execute(query).fetchall()

In [ ]:
dataframe = pd.read_sql(query, con = conn)

In [ ]:
dataframe

     CodeVehicule_id
0              84580
1             247732
2             247733
3             247734
4             247735
..               ...
149           299230
150           299231
151           299244
152           351780
153           510151

[154 rows x 1 columns]

In [ ]:
condition=(BonusMalus["CodeVehicule_id"].isin(dataframe["CodeVehicule_id"]))

In [ ]:
condition.value_counts()

False    1307195
True         166
Name: CodeVehicule_id, dtype: int64

In [ ]:
BonusMalus.loc[condition,'Fraud']=1

In [ ]:
BonusMalus['Fraud'].value_counts()

0    916858
1    390503
Name: Fraud, dtype: int64